# data constants
INPUT_SUFFIX = "_inputs"
OUTPUT_SUFFIX = "_outputs"
METADATA_SUFFIX = "_metadata"
PROTECTED_DATASET_SUFFIX = "trustyai_internal_"
PARTIAL_PAYLOAD_DATASET_NAME = "partial_payloads"
GROUND_TRUTH_SUFFIX = "-ground-truths"
METADATA_FILENAME = "metadata.json"
INTERNAL_DATA_FILENAME = "internal_data.csv"
# Payload parsing
TRUSTYAI_TAG_PREFIX = "_trustyai"
SYNTHETIC_TAG = f"{TRUSTYAI_TAG_PREFIX}_synthetic"
UNLABELED_TAG = f"{TRUSTYAI_TAG_PREFIX}_unlabeled"
BIAS_IGNORE_PARAM =  "bias-ignore"
# Prometheus constants
PROMETHEUS_METRIC_PREFIX = "trustyai_"